name: Testing runners

on: push

jobs:
  pytest:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - windows-latest
          - ubuntu-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test zipping (based systems)
        if: ${{ 'windows-latest' != matrix.platform }}
        run: zip -j target.zip hui/__main__.py
      - name: Test unzipping (based systems)
        if: ${{ 'windows-latest' != matrix.platform }}
        run: zip -sf target.zip
      - name: Test zipping (windows)
        if: ${{ 'windows-latest' == matrix.platform }}
        run: Compress-Archive -LiteralPath "hui\__main__.py" -DestinationPath "target.zip"
      - name: Test unzip (windows)
        if: ${{ 'windows-latest' == matrix.platform }}
        run: '[System.IO.Compression.ZipFile]::OpenRead("target.zip").Entries | ForEach-Object { $_.FullName }'
      - name: run ls
        shell: bash
        run: ls -la

