name: Testing runners

on: push

jobs:
  pytest:
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform:
          - windows-latest
          - ubuntu-latest
          - macOS-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test zipping (based systems)
        if: ${{ 'windows-latest' != matrix.platform }}
        run: zip -j target.zip hui/__main__.py
      - name: Test zipping (windows)
        if: ${{ 'windows-latest' == matrix.platform }}
        run: Compress-Archive -LiteralPath "hui\__main__.py" -DestinationPath "target.zip"
      - name: Test unzip (windows)
        if: ${{ 'windows-latest' == matrix.platform }}
        run: Expand-Archive -Path "target.zip" -DestinationPath "dest" -WhatIf
      - name: run ls
        shell: bash
        run: ls -la

