name: Testing runners

on: push

jobs:
  pytest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test zipping
        shell: bash
        run: zip -j target.zip hui/__main__.py
      - name: run ls
        shell: bash
        run: ls -la

